spring:
  application:
    name: crud-example-morsa

datasource:
  my-connection:
    jdbc-url: jdbc:mysql://localhost:3306/MIBDP?useSSL=false
    username: root
    password: Altair306M
    maximunm-pool-size: 10
    pool-name: "crud-pool"
    auto-commit: true